import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "../providers";
import { Inter } from "next/font/google";
import Link from "next/link";
import SignOutButton from "@/app/chat/SignOutButton";
const inter =  Inter({
  subsets: ['latin'],
  display: 'swap'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}>
      <div className="rounded-sm h-30 font-semibold flex items-center justify-between text-4xl pl-3">
        <div className="pl-15">Animate It 📽️</div>
        <div className="">Cursor For Video Creation 😎</div> 
        <SignOutButton />
      </div>
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  );
}
